on: push

jobs:
  secrets: # This is where you define your job's name
    runs-on: ubuntu-latest # Corrected typo in 'ubuntu-latest'
    steps:
      - run: | 
          import os
          print(len(os.getenv('MY_VAR')))
        shell: python 
        env:
          MY_VAR: ${{ secrets.MY_SECRET }}
