on: push

jobs:
  secrets: # This is where you define your job's name
    runs-on: ubuntu-latest # Corrected typo in 'ubuntu-latest'
    steps:
      - run: echo $MY_VAR
        env:
          MY_VAR: ${{ secrets.MY_SECRET }}
