name: trigger-demo
on:
  push: 
    branches:
      - main ### need to filter here
  pull_request:
  workflow_dispatch:

jobs:
  trigger-demo:
    runs-on: ubuntu # Corrected typo in 'ubuntu-latest'
    steps: 
      - run: echo "hello"
